<?xml version="1.0" encoding="utf-8"?><!DOCTYPE Representable [
        <!ELEMENT Representable (StructureMatrix)*>
        <!ATTLIST Representable
                class CDATA #REQUIRED>
        <!ELEMENT StructureMatrix (Data)*>
        <!ATTLIST StructureMatrix
                class CDATA #REQUIRED
                dim CDATA #REQUIRED
                name CDATA #REQUIRED
                typeClass CDATA #REQUIRED>
        <!ELEMENT Data (Cell)*>
        <!ATTLIST Data
                dim CDATA #REQUIRED>
        <!ELEMENT Cell (Representable|Double|Boolean|Integer)*>
        <!ATTLIST Cell
                c CDATA #REQUIRED
                l CDATA #REQUIRED>
        <!ELEMENT Double (#PCDATA)>
        <!ATTLIST Double
                class CDATA #REQUIRED>
        <!ELEMENT Boolean (#PCDATA)>
        <!ATTLIST Boolean
                class CDATA #REQUIRED>
        <!ELEMENT Integer (#PCDATA)>
        <!ATTLIST Integer
                class CDATA #REQUIRED>
        ]>
<Representable class="one.empty3.library.Scene">
    <StructureMatrix name="cameras/Caméras de la scène. cameraActive caméra en cours" dim="1" class="one.empty3.library.StructureMatrix" typeClass="one.empty3.library.Camera"><Data dim="1"><Cell l="0" c="0"><Representable class="one.empty3.library.Camera">
        <StructureMatrix name="matrice/matrice" dim="0" class="one.empty3.library.StructureMatrix" typeClass="one.empty3.library.Matrix33"><Data dim="0"><Cell l="0" c="0"><Representable class="one.empty3.library.Matrix33">
            <StructureMatrix name="d/3x3 matrix" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">1.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">-0.0</Double></Cell><Cell l="0" c="3"><Double class="class java.lang.Double">-0.0</Double></Cell><Cell l="0" c="4"><Double class="class java.lang.Double">1.0</Double></Cell><Cell l="0" c="5"><Double class="class java.lang.Double">-0.0</Double></Cell><Cell l="0" c="6"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="7"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="8"><Double class="class java.lang.Double">1.0</Double></Cell></Data></StructureMatrix></Representable>
        </Cell></Data></StructureMatrix><StructureMatrix name="eye/eye" dim="0" class="one.empty3.library.StructureMatrix" typeClass="one.empty3.library.Point3D"><Data dim="0"><Cell l="0" c="0"><Representable class="one.empty3.library.Point3D">
        <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">-100.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
    </Cell></Data></StructureMatrix><StructureMatrix name="angleX/angle horizontal caméra" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="0"><Cell l="0" c="0"><Double class="class java.lang.Double">1.0471975511965976</Double></Cell></Data></StructureMatrix><StructureMatrix name="angleY/angle vertical caméra" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="0"><Cell l="0" c="0"><Double class="class java.lang.Double">1.0471975511965976</Double></Cell></Data></StructureMatrix><StructureMatrix name="lookat/lookAt" dim="0" class="one.empty3.library.StructureMatrix" typeClass="one.empty3.library.Point3D"><Data dim="0"><Cell l="0" c="0"><Representable class="one.empty3.library.Point3D">
        <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
    </Cell></Data></StructureMatrix></Representable>
    </Cell><Cell l="0" c="1"><Representable class="one.empty3.library.Camera">
        <StructureMatrix name="matrice/matrice" dim="0" class="one.empty3.library.StructureMatrix" typeClass="one.empty3.library.Matrix33"><Data dim="0"><Cell l="0" c="0"><Representable class="one.empty3.library.Matrix33">
            <StructureMatrix name="d/3x3 matrix" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">1.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="3"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="4"><Double class="class java.lang.Double">1.0</Double></Cell><Cell l="0" c="5"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="6"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="7"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="8"><Double class="class java.lang.Double">1.0</Double></Cell></Data></StructureMatrix></Representable>
        </Cell></Data></StructureMatrix><StructureMatrix name="eye/eye" dim="0" class="one.empty3.library.StructureMatrix" typeClass="one.empty3.library.Point3D"><Data dim="0"><Cell l="0" c="0"><Representable class="one.empty3.library.Point3D">
        <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">-100.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
    </Cell></Data></StructureMatrix><StructureMatrix name="angleX/angle horizontal caméra" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="0"><Cell l="0" c="0"><Double class="class java.lang.Double">1.0471975511965976</Double></Cell></Data></StructureMatrix><StructureMatrix name="angleY/angle vertical caméra" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="0"><Cell l="0" c="0"><Double class="class java.lang.Double">1.0471975511965976</Double></Cell></Data></StructureMatrix><StructureMatrix name="lookat/lookAt" dim="0" class="one.empty3.library.StructureMatrix" typeClass="one.empty3.library.Point3D"><Data dim="0"><Cell l="0" c="0"><Representable class="one.empty3.library.Point3D">
        <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
    </Cell></Data></StructureMatrix></Representable>
    </Cell></Data></StructureMatrix><StructureMatrix name="lumieres/Lumières additionnelles" dim="1" class="one.empty3.library.StructureMatrix" typeClass="one.empty3.library.Lumiere"><Data dim="1"></Data></StructureMatrix><StructureMatrix name="cameraActive/cameraActive" dim="0" class="one.empty3.library.StructureMatrix" typeClass="one.empty3.library.Camera"><Data dim="0"><Cell l="0" c="0"><Representable class="one.empty3.library.Camera">
    <StructureMatrix name="matrice/matrice" dim="0" class="one.empty3.library.StructureMatrix" typeClass="one.empty3.library.Matrix33"><Data dim="0"><Cell l="0" c="0"><Representable class="one.empty3.library.Matrix33">
        <StructureMatrix name="d/3x3 matrix" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">1.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">-0.0</Double></Cell><Cell l="0" c="3"><Double class="class java.lang.Double">-0.0</Double></Cell><Cell l="0" c="4"><Double class="class java.lang.Double">1.0</Double></Cell><Cell l="0" c="5"><Double class="class java.lang.Double">-0.0</Double></Cell><Cell l="0" c="6"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="7"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="8"><Double class="class java.lang.Double">1.0</Double></Cell></Data></StructureMatrix></Representable>
    </Cell></Data></StructureMatrix><StructureMatrix name="eye/eye" dim="0" class="one.empty3.library.StructureMatrix" typeClass="one.empty3.library.Point3D"><Data dim="0"><Cell l="0" c="0"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">-100.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell></Data></StructureMatrix><StructureMatrix name="angleX/angle horizontal caméra" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="0"><Cell l="0" c="0"><Double class="class java.lang.Double">1.0471975511965976</Double></Cell></Data></StructureMatrix><StructureMatrix name="angleY/angle vertical caméra" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="0"><Cell l="0" c="0"><Double class="class java.lang.Double">1.0471975511965976</Double></Cell></Data></StructureMatrix><StructureMatrix name="lookat/lookAt" dim="0" class="one.empty3.library.StructureMatrix" typeClass="one.empty3.library.Point3D"><Data dim="0"><Cell l="0" c="0"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell></Data></StructureMatrix></Representable>
</Cell></Data></StructureMatrix><StructureMatrix name="objets/Objets à peindre" dim="1" class="one.empty3.library.StructureMatrix" typeClass="one.empty3.library.Representable"><Data dim="1"><Cell l="0" c="0"><Representable class="one.empty3.library.Polygon">
    <StructureMatrix name="points/point 0 à N du Polygone" dim="1" class="one.empty3.library.StructureMatrix" typeClass="one.empty3.library.Point3D"><Data dim="1"><Cell l="0" c="0"><Representable class="one.empty3.library.Point3D">
        <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">9.433181067208931</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">-4.431891381147484</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">-5.6652840268983145</Double></Cell></Data></StructureMatrix></Representable>
    </Cell><Cell l="0" c="1"><Representable class="one.empty3.library.Point3D">
        <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">6.756544415422903</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">7.856040466476742</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">6.3462850756452855</Double></Cell></Data></StructureMatrix></Representable>
    </Cell><Cell l="0" c="2"><Representable class="one.empty3.library.Point3D">
        <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">1.4599506325863576</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">8.869785621241952</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">-0.5327017795158451</Double></Cell></Data></StructureMatrix></Representable>
    </Cell><Cell l="0" c="3"><Representable class="one.empty3.library.Point3D">
        <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">0.5759676359255894</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">-5.036103780831162</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">-1.1717424534382004</Double></Cell></Data></StructureMatrix></Representable>
    </Cell><Cell l="0" c="4"><Representable class="one.empty3.library.Point3D">
        <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
    </Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="0" c="1"><Representable class="one.empty3.library.LumierePonctuelle">
    <StructureMatrix name="color/Couleur de la lumière" dim="0" class="one.empty3.library.StructureMatrix" typeClass="one.empty3.library.ColorTexture"><Data dim="0"><Cell l="0" c="0"></Cell></Data></StructureMatrix><StructureMatrix name="position/Position de la provenace lumineuse" dim="0" class="one.empty3.library.StructureMatrix" typeClass="one.empty3.library.Point3D"><Data dim="0"><Cell l="0" c="0"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell></Data></StructureMatrix><StructureMatrix name="directinal/isDirectional rayons parallèle et sphèrique" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Boolean"><Data dim="0"><Cell l="0" c="0"><Boolean class="class java.lang.Boolean">false</Boolean></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="0" c="2"><Representable class="one.empty3.library.core.nurbs.SurfaceParametriquePolynomialeBezier">
    <StructureMatrix name="startU/startU" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="0"><Cell l="0" c="0"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix><StructureMatrix name="maxX/ MaxX cordinates iterations for drawing - disable" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Integer"><Data dim="0"><Cell l="0" c="0"><Integer class="class java.lang.Integer">30</Integer></Cell></Data></StructureMatrix><StructureMatrix name="incrU/incrU" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="0"><Cell l="0" c="0"><Double class="class java.lang.Double">0.1</Double></Cell></Data></StructureMatrix><StructureMatrix name="incrV/incrV" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="0"><Cell l="0" c="0"><Double class="class java.lang.Double">0.1</Double></Cell></Data></StructureMatrix><StructureMatrix name="endU/endU" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="0"><Cell l="0" c="0"><Double class="class java.lang.Double">1.0</Double></Cell></Data></StructureMatrix><StructureMatrix name="power2/puissance par defaut #dim2" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Integer"><Data dim="0"><Cell l="0" c="0"><Integer class="class java.lang.Integer">5</Integer></Cell></Data></StructureMatrix><StructureMatrix name="maxY/ MaxY cordinates iterations for drawing - disable" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Integer"><Data dim="0"><Cell l="0" c="0"><Integer class="class java.lang.Integer">30</Integer></Cell></Data></StructureMatrix><StructureMatrix name="endV/endV" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="0"><Cell l="0" c="0"><Double class="class java.lang.Double">1.0</Double></Cell></Data></StructureMatrix><StructureMatrix name="cy/ Circulaire X last iterations for drawing - disable" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Boolean"><Data dim="0"><Cell l="0" c="0"><Boolean class="class java.lang.Boolean">false</Boolean></Cell></Data></StructureMatrix><StructureMatrix name="power1/puissance par defaut #dim1" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Integer"><Data dim="0"><Cell l="0" c="0"><Integer class="class java.lang.Integer">5</Integer></Cell></Data></StructureMatrix><StructureMatrix name="cx/ Circulaire X last iterations for drawing - disable" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Boolean"><Data dim="0"><Cell l="0" c="0"><Boolean class="class java.lang.Boolean">false</Boolean></Cell></Data></StructureMatrix><StructureMatrix name="startV/startV" dim="0" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="0"><Cell l="0" c="0"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix><StructureMatrix name="coefficients/points de contrôle" dim="2" class="one.empty3.library.StructureMatrix" typeClass="one.empty3.library.Point3D"><Data dim="2"><Cell l="0" c="0"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">2.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">-2.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="0" c="1"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">2.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">-1.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="0" c="2"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">2.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="0" c="3"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">2.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">1.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="0" c="4"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">2.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">2.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="1" c="5"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">1.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">-2.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="1" c="6"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">1.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">-1.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="1" c="7"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">1.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="1" c="8"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">1.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">1.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="1" c="9"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">1.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">2.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="2" c="10"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">-2.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="2" c="11"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">-1.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="2" c="12"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="2" c="13"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">1.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="2" c="14"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">2.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="3" c="15"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">-1.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">-2.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="3" c="16"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">-1.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">-1.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="3" c="17"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">-1.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="3" c="18"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">-1.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">1.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="3" c="19"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">-1.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">2.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="4" c="20"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">-2.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">-2.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="4" c="21"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">-2.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">-1.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="4" c="22"><Representable class="one.empty3.library.Point3D">
    <StructureMatrix name="coordArr/coordonnées" dim="1" class="one.empty3.library.StructureMatrix" typeClass="java.lang.Double"><Data dim="1"><Cell l="0" c="0"><Double class="class java.lang.Double">-2.0</Double></Cell><Cell l="0" c="1"><Double class="class java.lang.Double">0.0</Double></Cell><Cell l="0" c="2"><Double class="class java.lang.Double">0.0</Double></Cell></Data></StructureMatrix></Representable>
</Cell><Cell l="4" c="23"><Representable class="one.empty3.library.Point3D">